### PR TITLE
Fix/autolayout sizing

### PR DESCRIPTION
**Pull request by SushiRoll53**

### CODE REVIEW

**Comment by ivan-015** [comment]
The `Save` Button in `AdminCitySectionEditScreen` does not scale correctly. Here's Figma:

image


Here's the conversion:

image

In addition, it seems like the orca city icon box is shrinking as you can see in the overflow of the image above 🤔

**Comment by ivan-015** [comment]
Also, it seems like the login screen is still faulty for the constraints: 
image

image

**Comment by ivan-015** [comment]
Another thing I noticed, that I'm not sure if it has to do with AutoLayout constraints is that when you scale horizontally, the cities in the header stay together:
image

However, on the generation, as you scale horizontally, the cities become more separated:
image

Update: This is the generation in dev, the cities to stay together:
image



Another thing I hadn't noticed is the text getting cut off 🤔 Also not sure if that has to do with AutoLayout

**Comment by SushiRoll53** [comment]
For these issues the inconsistencies came more from the actual Figma file. I modified the Figma file to produce the right output. Let me know if there are any other issues to solve.

**Review by ivan-015 — CHANGES_REQUESTED** [review]
I'm still seeing issues with the scaling. For example, see the following `Save` button. Now it's scaling up and down instead of just staying centered 🤔 

image

In the design, here's what happens when we scale down this button 
image

**Comment by ivan-015** [comment]
The save button is still not scaling properly 🤔 

Here's the gen:
image

And here's the figma file when scaling:
image


Also, we're still receiving that overflow in the images in the header when scaling down. I have a suspicion that may also be because of the AutoLayout constraints

**Comment by SushiRoll53** [comment]
This branch will be merge to a new branch with additional changes, a new PR will be created

**Pull request closed without merging**
