### PR TITLE
Release/1.4.0

### PR DESCRIPTION
**Pull request by ivan-015**
* Added support for Prototyping in FIgma!
* Fixed state management nodes having incorrect layout
* Minor improvements

### CODE REVIEW

**Review by SushiRoll53 — APPROVED** [review]
LGTM

**Comment by SushiRoll53** [comment]
You need to update the `pubspec.yaml`

**Review by siliconivan — APPROVED** [review]
LGTM!

**Comment by ivan-015** [comment]
Closing this PR because it merged successfully into stable but for some reason the PR doesn't reflect that.

**Pull request closed without merging**
