### PR TITLE
Release/1.4.1

### PR DESCRIPTION
**Pull request by ivan-015**
* Added overridable properties to bloc states
* Fixed minor bug for figma prototyping

### CODE REVIEW

**Review by SushiRoll53 — COMMENTED** [review]
We forgot to update pubspec.yaml

**Comment by ivan-015** [comment]
> We forgot to update pubspec.yaml

No sir, version 1.4.1

**Review by SushiRoll53 — APPROVED** [review]
You are right, LGTM

**Review by siliconivan — APPROVED** [review]
lgtm

**Pull request merged**
