### PR TITLE
Remove unused property in PBIntermediateNode

### LINKED ISSUE #31: Removing unused attribute.
## Change Proposal
Removing the property `widgetType` from `PBIntermediateNodes`

### Module and Current Solution
Right now there is no purpose of this attribute, this attribute was used in the past for identifying `PBGenerator`s.

## Benefits of the Change
It would Improve readability in the code.

### PR DESCRIPTION
**Pull request by BLKKKBVSIK**
I was hoping to fix #31  .
I just remove the property and didnt find any usage of the property in the project.

### CODE REVIEW

**Comment by siliconivan** [comment]
Thanks! You are correct, we've been meaning to remove this as it's not being used anymore. You're welcome to join our Discord by the way so I can award you a feather!

**Review by siliconivan — APPROVED** [review]
LGTM

**Review by Ihuds577 — COMMENTED** [review]
LGTM

**Review by Ihuds577 — APPROVED** [review]
LGTM (missed the approve button)

**Pull request merged**
