### PR TITLE
Update CONTRIBUTING.md

### LINKED ISSUE #89: Update the CONTRIBUTING.MD
Fix the documentation and update the file

### PR DESCRIPTION
**Pull request by kichloo**
Closes #89

### CODE REVIEW

**Review by x64Eddie — APPROVED** [review]
LGTM

**Review by ivan-015 — APPROVED** [review]
Looks good to me!

**Comment by kichloo** [comment]
Hi @x64Eddie. Just wanted to know whether this organisation is a part of Hacktoberfest

**Comment by siliconivan** [comment]
Hey @kichloo, we do not have any direct association with Hacktoberfest other than that we are simply an open-source project! PR's to Parabeac-Core should work for Hacktoberfest though & we are in fact promoting ourselves to be working with developers that want to participate in Hacktoberfest.

**Comment by kichloo** [comment]
@siliconivan Ok.I was asking so that this PR could count towards completion of the PR through the 'Hacktoberfest-accepted' label. No problem!

**Comment by kichloo** [comment]
@siliconivan @x64Eddie @ivan-015 Any update on the Hacktoberfest swags of Parabeac Core? I had made a PR which was merged in the month of October

**Comment by siliconivan** [comment]
Hey @kichloo can you DM me in Discord? We can sort this out there :)

**Pull request merged**
