### PR TITLE
(fix:#51) Refactored PBParam to PBVariable

### LINKED ISSUE #51: Change PBParam to PBVariable
## Change Proposal
Change the name of the class of PBParam to PBVariable.

### Module and Current Solution
This should just make more sense since Params are describing something more like a variable.

## Benefits of the Change
Improve Readability.

### PR DESCRIPTION
**Pull request by haardikdharma10**
This PR aims to solve the issue #51. Changed the name of the class PBParam to PBVariable and made the necessary changes in other dart files.

### CODE REVIEW

**Comment by siliconivan** [comment]
Sweet, at first glance. This looks good. We're getting together today to test and merge all PRs today. The only thing is that we have to update the parabeac_eggs and parabeac_egg_template repo. Let us know if you'd want to take a whack at that.

**Comment by haardikdharma10** [comment]
@siliconivan, thanks! Surely, i'd give it a go.

**Review by x64Eddie — APPROVED** [review]
LGTM

**Review by ivan-015 — APPROVED** [review]
LGTM!

**Pull request merged**
